kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: xKernel Compilation
   image: xyzuan/xdocker:latest
   environment:
   clang:
     - bash kernel_build.sh
   gcc:
     - bash gcc_build.sh
