kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: xKernel Compilation
   image: xyzuan/xdocker:latest
   environment:
     ANYKERNEL:
       from_secret: ANYKERNEL
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
   commands:
     - bash build.sh
